---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cr-build
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: image-url
      description: The image url in your container registry
    - name: path-to-dockerfile
      default: "."
    - name: Repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: apikeyscan
      description: doi plugin
    - name: dockerconfigjson
      description: registry secret      
    - name: registry-namespace
      description: the ibmcloud registry namespace
    - name: registry-region
      description: the ibmcloud registry region
      default: us-south
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: prod
    - name: image-url
      description: image to scan
    - name: account
      description: account info
    - name: password
      description: password of the account
    - name: app-name
      description: Logical application name for DevOps Insights
    - name: resourcegroup
      description: toolchain resource group
    - name: toolchain-id
      description: |
        Toolchain service instance id.
        Default to the toolchain containing the CD Tekton PipelineRun currently executed
      default: ""
    - name: pipeline-debug
      default: 0
    - name: fail-on-lint-errors
      description: force failure of task when docker lint errors are found
      default: "true"
    - name: build-args
      description: ibmcloud cr build argument list in the format 'KEY=VALUE' with a key-value pair per line.
      default: ""
    - name: fail-on-scanned-issues
      description: force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: pr-url
      description: PR url
    - name: apikey
    - name: commit-timestamp
      description: commit timestamp
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""
    - name: commons-hosted-region
      default: ""



  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: image-to-build
      spec:
        type: image
        params:
          - name: url
            value: $(params.image-url)
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cr-build-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: eyJhdXRocyI6eyJ1cy5pY3IuaW8iOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6InZsS2pQTlF2Tng2dlhydnB5WnlCeUxNLS1WMi1tazc5elpMTVlieTREbjJHIiwiYXV0aCI6ImFXRnRZWEJwYTJWNU9uWnNTMnBRVGxGMlRuZzJkbGh5ZG5CNVdubENlVXhOTFMxV01pMXRhemM1ZWxwTVRWbGllVFJFYmpKSCJ9fX0=
      metadata:
        name: docker-auth-for-tekton
      type: kubernetes.io/dockerconfigjson  
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: build-bot
      imagePullSecrets:  
        - name: docker-auth-for-tekton

    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: cr-build-$(uid)
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: cr-build
        resources:
          - name: app-image
            resourceRef:
              name: image-to-build
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: Repository
            value: $(params.Repository)
          - name: revision
            value: $(params.revision)
          - name: apikey
            value: $(params.apikey)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: registry-region
            value: $(params.registry-region)
          - name: cluster
            value: $(params.cluster)
          - name: clusterRegion
            value: $(params.clusterRegion)
          - name: clusterNamespace
            value: $(params.clusterNamespace)
          - name: image-url
            value: $(params.image-url)
          - name: account
            value: $(params.account)
          - name: password
            value: $(params.password)
          - name: app-name
            value: $(params.app-name)
          - name: resourcegroup
            value: $(params.resourcegroup)
          - name: toolchain-id
            value: $(params.toolchain-id)
          - name: apikeyscan
            value: $(params.apikeyscan)
          - name: build-args
            value: $(params.build-args)
          - name: fail-on-scanned-issues
            value: $(params.fail-on-scanned-issues)
          - name: pr-url
            value: $(params.pr-url)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id)
          - name: commons-hosted-region
            value: $(params.commons-hosted-region)


         
          
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: cr-build-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cr-build
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cr-build
spec:
  triggers:
    - binding:
        name: cr-build
      template:
        name: cr-build
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/Shraddha8269/tekton-twistlock"
    - name: revision
      value: "main"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: cr-build

